# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'straightPoolSheet' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for straightPoolSheet
  pod 'Firebase/Core'


  pod 'RNLanguages', :path => '../node_modules/react-native-languages'
  pod 'React', :path => '../node_modules/react-native', :subspecs => ['RCTImage']
  pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga'

  pod 'RNSVG', :path => '../node_modules/react-native-svg'

  target 'straightPoolSheetTests' do
    inherit! :search_paths
    # Pods for testing
    pod 'Firebase/Core'
  end

end
